version: 2.0
jobs:
  build:
    docker:
      - image: takahiroi/suilog_app:latest
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: test_suilog_db
          - DB_USERNAME: root
 
      - image: takahiroi/suilog_db:latest
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: test_suilog_db

    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: dockerize のインストール
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: db の待機
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: echo "APP_KEY=" > .env.testing
      - run: php artisan key:generate
      - run: php artisan migrate:refresh --seed
      - run:
          name: php test
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: takahiroi/suilog_app:latest
    steps:
      - add_ssh_keys
      - run:
          name: deploy 
          command: | # シードを入れたい時はこれを、php artisan migrate:refresh --seed --force && \
            ssh -o StrictHostKeyChecking=no -t webapp@${HOST_NAME} "cd suilog_product && \
              git pull origin master && \
              composer install -n --no-dev --prefer-dist && \ 
              php artisan config:cache" 


workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master